"""Data models for tokenaudit.

All domain objects are frozen dataclasses so reports are immutable once built.
Token counts are integers; costs are floats in USD.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from datetime import datetime, timezone


@dataclass(frozen=True)
class Usage:
    """Token usage for a single message/turn."""

    input_tokens: int = 0
    output_tokens: int = 0
    cache_creation_tokens: int = 0
    cache_read_tokens: int = 0

    @property
    def total(self) -> int:
        return self.input_tokens + self.output_tokens

    @property
    def total_with_cache(self) -> int:
        return (
            self.input_tokens
            + self.output_tokens
            + self.cache_creation_tokens
            + self.cache_read_tokens
        )


@dataclass
class Message:
    """A single turn in an agent session transcript."""

    role: str  # "user" | "assistant" | "system"
    usage: Usage
    model: Optional[str] = None
    content: object = None  # str or list[dict] (content blocks)
    # Bookkeeping populated by the parser:
    has_tool_use: bool = False
    has_tool_result: bool = False
    file_reads: tuple = field(default_factory=tuple)  # tuple[str, ...]


@dataclass
class Session:
    """A parsed agent session."""

    source: str
    messages: list = field(default_factory=list)
    agent: str = "unknown"  # claude-code | opencode | generic


@dataclass(frozen=True)
class PhaseBreakdown:
    """Where the input/output tokens went, by phase."""

    preread_input: int = 0  # input consumed before the first tool call (setup/context)
    tool_result_input: int = 0  # input from tool outputs returned to the model
    other_input: int = 0  # text-only user turns, summaries, etc.
    generation_output: int = 0  # output tokens generated by the model

    @property
    def total_input(self) -> int:
        return self.preread_input + self.tool_result_input + self.other_input


@dataclass(frozen=True)
class FileRead:
    path: str
    read_count: int
    est_input_tokens: int  # estimated input tokens attributable to reads of this file


@dataclass(frozen=True)
class WasteFinding:
    """A diagnosed inefficiency."""

    kind: str  # PRE_READ_OVERHEAD | REDUNDANT_READS | TELEMETRY_OVERHEAD | CONTEXT_BLOAT
    severity: str  # INFO | WARN | HIGH
    detail: str
    wasted_tokens: int
    wasted_cost: float


@dataclass(frozen=True)
class Recommendation:
    title: str
    detail: str
    potential_savings_pct: Optional[float] = None


@dataclass
class CostReport:
    session: str
    agent: str
    total_input: int = 0
    total_output: int = 0
    total_cost: float = 0.0
    by_model: dict = field(default_factory=dict)
    phase: PhaseBreakdown = field(default_factory=PhaseBreakdown)
    file_reads: list = field(default_factory=list)
    findings: list = field(default_factory=list)
    recommendations: list = field(default_factory=list)

    @property
    def wasted_cost(self) -> float:
        return sum(f.wasted_cost for f in self.findings)

    @property
    def wasted_tokens(self) -> int:
        return sum(f.wasted_tokens for f in self.findings)

    def as_dict(self) -> dict:
        return {
            "session": self.session,
            "agent": self.agent,
            "total_input": self.total_input,
            "total_output": self.total_output,
            "total_cost": round(self.total_cost, 4),
            "wasted_cost": round(self.wasted_cost, 4),
            "wasted_tokens": self.wasted_tokens,
            "by_model": {k: round(v, 4) for k, v in self.by_model.items()},
            "phase": {
                "preread_input": self.phase.preread_input,
                "tool_result_input": self.phase.tool_result_input,
                "other_input": self.phase.other_input,
                "generation_output": self.phase.generation_output,
            },
            "file_reads": [
                {"path": fr.path, "read_count": fr.read_count,
                 "est_input_tokens": fr.est_input_tokens}
                for fr in self.file_reads
            ],
            "findings": [
                {
                    "kind": f.kind,
                    "severity": f.severity,
                    "detail": f.detail,
                    "wasted_tokens": f.wasted_tokens,
                    "wasted_cost": round(f.wasted_cost, 4),
                }
                for f in self.findings
            ],
            "recommendations": [
                {"title": r.title, "detail": r.detail,
                 "potential_savings_pct": r.potential_savings_pct}
                for r in self.recommendations
            ],
        }
